
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author David
 */
public class Dialog_ImageInformation extends javax.swing.JDialog {

    /**
     * Creates new form Dialog_ImageInformation
     */
    public Dialog_ImageInformation(java.awt.Frame parent, boolean modal, String imagePath) {
        super(parent, modal);
        initComponents();
        this.imagePath = imagePath;
        setInfo();
    }
    
    public void setImagePath(String path) {
        this.imagePath = path;
        if(origImagePath == null) origImagePath = path;
        
        if(!imagePath.equals(origImagePath)) {
            setInfo();
        }
    }

    private void setInfo() {
        boolean reset = false;
        if (this.origImagePath == null) {
            reset = true;
        } else if (!this.origImagePath.equals(imagePath)) {
            reset = true;
        }
        if (reset) {
            origImagePath = imagePath;
            path = new File(imagePath);
            info = new Headless_ImageInfo(imagePath);//inefficient!!
            icon = new ImageIcon(imagePath);//Inefficient!!
            image = icon.getImage();
            
        }
        imageScaled = image.getScaledInstance(this.Panel_ImagePanel.getWidth(), this.Panel_ImagePanel.getHeight() * info.getHeight() / info.getWidth(), java.awt.Image.SCALE_SMOOTH);
        this.ImageIcon_Image.setIcon(new ImageIcon(imageScaled));
        this.Label_Directory.setText("Directory: " + path.getParent());
        this.Label_Name.setText("File name: " + path.getName());
        this.Label_Mime.setText("Format: " + info.getFormat());
        this.Label_Width.setText("Image width (DPI | pixels | inches): (" + info.getDPIWidth() + " | " + info.getWidth() + " | " + info.getWidthInches() + ")");
        this.Label_Height.setText("Image height (DPI | pixels | inches): (" + info.getDPIHeight() + " | " + info.getHeight() + " | " + info.getHeightInches() + ")");
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Name = new javax.swing.JLabel();
        Label_Directory = new javax.swing.JLabel();
        Label_Mime = new javax.swing.JLabel();
        Label_Width = new javax.swing.JLabel();
        Label_Height = new javax.swing.JLabel();
        Button_OK = new javax.swing.JButton();
        Panel_ImagePanel = new javax.swing.JPanel();
        ImageIcon_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Label_Name.setText("Image Name");

        Label_Directory.setText("Image Directory");

        Label_Mime.setText("Mime Type");

        Label_Width.setText("Width (DPI | Inches | Pixels)");

        Label_Height.setText("Height (DPI | Inches | Pixels)");

        Button_OK.setText("OK");
        Button_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_OKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ImagePanelLayout = new javax.swing.GroupLayout(Panel_ImagePanel);
        Panel_ImagePanel.setLayout(Panel_ImagePanelLayout);
        Panel_ImagePanelLayout.setHorizontalGroup(
            Panel_ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ImagePanelLayout.createSequentialGroup()
                .addComponent(ImageIcon_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_ImagePanelLayout.setVerticalGroup(
            Panel_ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageIcon_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_ImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Height)
                            .addComponent(Button_OK)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Label_Mime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Directory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Width, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_ImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Directory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Mime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Width)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Height)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_OK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_OKMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_Button_OKMouseClicked

    String imagePath;
    String origImagePath;

    File path;
    Headless_ImageInfo info;
    ImageIcon icon;//Inefficient!!
    Image image;
    Image imageScaled;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_OK;
    private javax.swing.JLabel ImageIcon_Image;
    private javax.swing.JLabel Label_Directory;
    private javax.swing.JLabel Label_Height;
    private javax.swing.JLabel Label_Mime;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_Width;
    private javax.swing.JPanel Panel_ImagePanel;
    // End of variables declaration//GEN-END:variables
}
