/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author David
 */
public class Frame_NoteTaker extends javax.swing.JFrame {

    /**
     * Creates new form Frame_NoteTaker
     */
    public Frame_NoteTaker(Frame_DataSampler fds) {
        initComponents();
        this.fds = fds;
        this.notes = this.fds.notes;
        this.TextArea_Notes.setText(notes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Save = new javax.swing.JButton();
        Button_Cancel = new javax.swing.JButton();
        Label_Notes = new javax.swing.JLabel();
        ScrollPane_TextArea = new javax.swing.JScrollPane();
        TextArea_Notes = new javax.swing.JTextArea();
        Button_SaveAndExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_Save.setText("Save");
        Button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveActionPerformed(evt);
            }
        });

        Button_Cancel.setText("Cancel");
        Button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelActionPerformed(evt);
            }
        });

        Label_Notes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label_Notes.setText("Provide Notes Below");

        TextArea_Notes.setColumns(20);
        TextArea_Notes.setRows(5);
        ScrollPane_TextArea.setViewportView(TextArea_Notes);

        Button_SaveAndExit.setText("Save and Exit");
        Button_SaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveAndExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Notes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_SaveAndExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Cancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ScrollPane_TextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Label_Notes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_TextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Save)
                            .addComponent(Button_Cancel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_SaveAndExit)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveActionPerformed

        fds.notes = this.TextArea_Notes.getText();
        fds.writeNotesToFile(fds.notes);
        //this.setVisible(false);
        //this.dispose();

    }//GEN-LAST:event_Button_SaveActionPerformed

    public void updateNotes() {
       this.TextArea_Notes.setText(fds.notes);
    }
    
    private void Button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_Button_CancelActionPerformed

    private void Button_SaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveAndExitActionPerformed
       fds.notes = this.TextArea_Notes.getText();
        fds.writeNotesToFile(fds.notes);
        this.setVisible(false);
    }//GEN-LAST:event_Button_SaveAndExitActionPerformed

    Frame_DataSampler fds;
    String notes;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancel;
    private javax.swing.JButton Button_Save;
    private javax.swing.JButton Button_SaveAndExit;
    private javax.swing.JLabel Label_Notes;
    private javax.swing.JScrollPane ScrollPane_TextArea;
    private javax.swing.JTextArea TextArea_Notes;
    // End of variables declaration//GEN-END:variables
}
