
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author David
 */
public class Frame_SetUserInfo extends javax.swing.JFrame {

    /**
     * Creates new form Frame_SetUserInfo
     */
    public Frame_SetUserInfo(Frame_DataSampler fds) {
        initComponents();
        this.fds = fds;
        time = new Date().getTime();

        String directory = getDirectoryFromFile();
        if (directory == null) {
            this.TextField_RootDirectory.setText(fds.rootDirectory);
        } else {
            this.TextField_RootDirectory.setText(directory);
        }
        /*
        this.TextField_Attributes.setText(fds.defaultAttributesDirectory);
        this.TextField_Characters.setText(fds.defaultCharactersDirectory);
        this.TextField_Images.setText(fds.defaultImagesDirectory);
        this.TextField_Samples.setText(fds.defaultSamplesDirectory);
        this.TextField_K.setText(Integer.toString(fds.kDefault));
        this.TextField_Small.setText(Integer.toString(fds.defaultLocalSize));
        this.TextField_Medium.setText(Integer.toString(fds.defaultWindowSize));
        this.TextField_Large.setText(Integer.toString(fds.defaultOverviewSize));
        this.TextField_MinimumSize.setText(Integer.toString(fds.defaultImageWidth));
         */
        fsrd = new Frame_SelectRootDirectory(this);
        if (this.TextField_RootDirectory.getText().length() > 0) {
            fsrd.setDirectory(this.TextField_RootDirectory.getText());
        }
    }

    private String getDirectoryFromFile() {
        String defaultFile = "root.directory";
        try {
            if (Files.exists(Paths.get(defaultFile))) {
                BufferedReader br = new BufferedReader(new FileReader(defaultFile));
                String root = br.readLine();
                br.close();
                if (root != null) {
                    if (root.length() > 0) {
                        return root;
                    }
                }
            } else {
                return null;
            }
        } catch (Exception e) {
            return null;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Title = new javax.swing.JLabel();
        Button_OK = new javax.swing.JButton();
        Button_Cancel = new javax.swing.JButton();
        Panel_SessionInfo = new javax.swing.JPanel();
        Label_Name = new javax.swing.JLabel();
        TextField_Name = new javax.swing.JTextField();
        Label_Session = new javax.swing.JLabel();
        TextField_Session = new javax.swing.JTextField();
        Panel_Directories = new javax.swing.JPanel();
        TextField_RootDirectory = new javax.swing.JTextField();
        Button_RootDirectory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Label_Title.setText("Set your name and session name");

        Button_OK.setText("OK");
        Button_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_OKMouseClicked(evt);
            }
        });

        Button_Cancel.setText("Cancel");
        Button_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_CancelMouseClicked(evt);
            }
        });

        Panel_SessionInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Session Information"));

        Label_Name.setText("Name:");

        TextField_Name.setColumns(25);
        TextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_NameKeyPressed(evt);
            }
        });

        Label_Session.setText("Project Name:");

        TextField_Session.setColumns(25);
        TextField_Session.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_SessionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout Panel_SessionInfoLayout = new javax.swing.GroupLayout(Panel_SessionInfo);
        Panel_SessionInfo.setLayout(Panel_SessionInfoLayout);
        Panel_SessionInfoLayout.setHorizontalGroup(
            Panel_SessionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SessionInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_SessionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Name)
                    .addComponent(Label_Session))
                .addGap(65, 65, 65)
                .addGroup(Panel_SessionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_Session)
                    .addComponent(TextField_Name))
                .addContainerGap())
        );
        Panel_SessionInfoLayout.setVerticalGroup(
            Panel_SessionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SessionInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_SessionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Name)
                    .addComponent(TextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_SessionInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Session))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Directories.setBorder(javax.swing.BorderFactory.createTitledBorder("Directory Information"));

        TextField_RootDirectory.setEditable(false);
        TextField_RootDirectory.setColumns(25);

        Button_RootDirectory.setText("Root Directory:");
        Button_RootDirectory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_RootDirectoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_DirectoriesLayout = new javax.swing.GroupLayout(Panel_Directories);
        Panel_Directories.setLayout(Panel_DirectoriesLayout);
        Panel_DirectoriesLayout.setHorizontalGroup(
            Panel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DirectoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_RootDirectory)
                .addGap(30, 30, 30)
                .addComponent(TextField_RootDirectory)
                .addContainerGap())
        );
        Panel_DirectoriesLayout.setVerticalGroup(
            Panel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DirectoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DirectoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_RootDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_RootDirectory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Title)
                    .addComponent(Panel_Directories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_SessionInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_SessionInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Directories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_OK)
                    .addComponent(Button_Cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NameKeyPressed
        Frame_Parameters.setStandardCharacterSetEditable(evt, TextField_Name);
    }//GEN-LAST:event_TextField_NameKeyPressed

    private void TextField_SessionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_SessionKeyPressed
        Frame_Parameters.setStandardCharacterSetEditable(evt, TextField_Session);
    }//GEN-LAST:event_TextField_SessionKeyPressed

    private void Button_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_OKMouseClicked
        name = this.TextField_Name.getText();
        session = this.TextField_Session.getText();
        fds.rootDirectory = this.TextField_RootDirectory.getText();
        //session = session + "_" + time;

        if (name.length() <= 0 || session.length() <= 0 || fds.rootDirectory.length() <= 0) {
            JOptionPane.showMessageDialog(this, "You must provide your name, a label for this session, and a project root directory to continue with this application. Quitting.");
            System.exit(0);
        }
        fds.projectName = session;
        fds.user = name;

        /*
        fds.rootDirectory = this.TextField_RootDirectory.getText();
        fds.defaultAttributesDirectory = this.TextField_Attributes.getText();
        fds.defaultCharactersDirectory = this.TextField_Characters.getText();
        fds.defaultImagesDirectory = this.TextField_Images.getText();
        fds.defaultSamplesDirectory = this.TextField_Samples.getText();

        fds.kDefault = Integer.parseInt(this.TextField_K.getText());
        fds.defaultLocalSize = Integer.parseInt(this.TextField_Small.getText());
        fds.defaultWindowSize = Integer.parseInt(this.TextField_Medium.getText());
        fds.defaultOverviewSize = Integer.parseInt(this.TextField_Large.getText());
        fds.defaultImageWidth = Integer.parseInt(this.TextField_MinimumSize.getText());
         */
 /*
        //make and use a static method that checks / creates the directories as needed!!;
        try {
            Files.createDirectories(Paths.get(fds.rootDirectory + File.separator + fds.defaultImagesDirectory));
        } catch (IOException ex) {

            //Logger.getLogger(Frame_Parameters.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Could not create Images directory. Be sure your path information is valid. Quitting.");
            System.exit(0);
        }

        try {
            Files.createDirectories(Paths.get(fds.rootDirectory + File.separator + fds.defaultCharactersDirectory));
        } catch (IOException ex) {
            //Logger.getLogger(Frame_Parameters.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Could not create Characters directory. Be sure your path information is valid. Quitting.");
            System.exit(0);

        }

        try {
            Files.createDirectories(Paths.get(fds.rootDirectory + File.separator + fds.defaultAttributesDirectory));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Could not create Attributes directory. Be sure your path information is valid. Quitting.");
            System.exit(0);

            //Logger.getLogger(Frame_Parameters.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Files.createDirectories(Paths.get(fds.rootDirectory + File.separator + fds.defaultSamplesDirectory));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Could not create Samples directory. Be sure your path information is valid. Quitting.");
            System.exit(0);

            //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!make and use a static method to set / check all the directories;
                        Samples directory structure:;
            Samples project folder;
                file mapping file (train, test, validate);
                validation folder;
                    validation sample metadata;
                    pixel folder;
                    local folder;
                    window folder;
                    overview folder;
                    montage folder;
                training folder;
                    training sample metadata;
                    pixel folder;
                    local folder;
                    window folder;
                    overview folder;
                    montage folder;
                testing folder;
                    testing sample metadata;
                    pixel folder;
                    local folder;
                    window folder;
                    overview folder;
                    montage folder;
            
//Logger.getLogger(Frame_Parameters.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            if (session.length() == 0) {
                JOptionPane.showMessageDialog(this, "Could not create Project Samples directory. Be sure your path information is valid and that your Project Name is entered. Quitting.");
                System.exit(0);
            }
            Files.createDirectories(Paths.get(fds.rootDirectory + File.separator + fds.defaultSamplesDirectory + File.separator + session));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Could not create Project Samples directory. Be sure your path information is valid and that your Project Name is entered. Quitting.");
            System.exit(0);

//Logger.getLogger(Frame_Parameters.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
        fds.initializeDataFromDefaults();
        fds.pack();
        fds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_OKMouseClicked

    private void Button_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Button_CancelMouseClicked

    private void Button_RootDirectoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_RootDirectoryMouseClicked
        this.fsrd.setVisible(true);
    }//GEN-LAST:event_Button_RootDirectoryMouseClicked

    public void setRootDirectory(String directory) {
        this.TextField_RootDirectory.setText(directory);
    }

    public String getRootDirectory() {
        return this.TextField_RootDirectory.getText();
    }

    Frame_SelectRootDirectory fsrd;
    Frame_DataSampler fds;
    String name;
    String session;
    long time = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancel;
    private javax.swing.JButton Button_OK;
    private javax.swing.JButton Button_RootDirectory;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_Session;
    private javax.swing.JLabel Label_Title;
    private javax.swing.JPanel Panel_Directories;
    private javax.swing.JPanel Panel_SessionInfo;
    private javax.swing.JTextField TextField_Name;
    private javax.swing.JTextField TextField_RootDirectory;
    private javax.swing.JTextField TextField_Session;
    // End of variables declaration//GEN-END:variables
}
