
import java.io.File;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author dhearn
 */
public class Frame_SelectCharactersFileBrowser extends javax.swing.JFrame {

    /**
     * Creates new form SelectCharactersFileBrowser
     */
    public Frame_SelectCharactersFileBrowser(Frame_DataSampler f_ds) {
        this.f_ds = f_ds;

        initComponents();
        if (f_ds.getRootDirectory() != null) {
            currentDirectory = f_ds.getRootDirectory() + File.separator + f_ds.defaultCharactersDirectory;
            SelectCharactersFile.setCurrentDirectory(new File(currentDirectory));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectCharactersFile = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectCharactersFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCharactersFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SelectCharactersFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SelectCharactersFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectCharactersFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCharactersFileActionPerformed

        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            String path = SelectCharactersFile.getSelectedFile().getAbsolutePath();
            currentDirectory = SelectCharactersFile.getCurrentDirectory().getAbsolutePath();
            f_ds.setCharacterList(path);
            f_ds.setProjectCharactersFile();
            if (f_ds.getRootDirectory() == null) {
                f_ds.setRootDirectory(SelectCharactersFile.getCurrentDirectory().getParentFile().getAbsolutePath());
            }
            this.setVisible(false);
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.setVisible(false);
        }


    }//GEN-LAST:event_SelectCharactersFileActionPerformed

    public void setDirectory() {
        try {
            SelectCharactersFile.setCurrentDirectory(new File(currentDirectory));
        } catch (Exception e) {
            //System.out.println("Directory not set");
        }
    }
    private String currentDirectory;
    private Frame_DataSampler f_ds;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser SelectCharactersFile;
    // End of variables declaration//GEN-END:variables
}
