

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author David
 */
public class Frame_SelectionColors extends javax.swing.JFrame {

    /**
     * Creates new form Frame_ColorPalette
     */
    public Frame_SelectionColors(Frame_DataSampler fds) {
        initComponents();
        this.fds = fds;
        this.setColors();
        this.fcc = new Frame_ColorChooser(Button_BoxRandom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_OK = new javax.swing.JButton();
        Button_Cancel = new javax.swing.JButton();
        Panel_Boxes = new javax.swing.JPanel();
        Button_BoxSelected = new javax.swing.JButton();
        Button_BoxRandom = new javax.swing.JButton();
        Panel_Main = new javax.swing.JPanel();
        Button_PointSelected = new javax.swing.JButton();
        Button_PointRandom = new javax.swing.JButton();
        Button_PointSampled = new javax.swing.JButton();
        Panel_Zoom = new javax.swing.JPanel();
        Button_PointZoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_OK.setText("OK");
        Button_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_OKMouseClicked(evt);
            }
        });

        Button_Cancel.setText("Cancel");
        Button_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_CancelMouseClicked(evt);
            }
        });

        Panel_Boxes.setBorder(javax.swing.BorderFactory.createTitledBorder("Boxes"));

        Button_BoxSelected.setText("Selected");
        Button_BoxSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_BoxSelectedMouseClicked(evt);
            }
        });

        Button_BoxRandom.setText("Random");
        Button_BoxRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_BoxRandomMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_BoxesLayout = new javax.swing.GroupLayout(Panel_Boxes);
        Panel_Boxes.setLayout(Panel_BoxesLayout);
        Panel_BoxesLayout.setHorizontalGroup(
            Panel_BoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BoxesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_BoxSelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_BoxRandom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BoxesLayout.setVerticalGroup(
            Panel_BoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BoxesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_BoxSelected)
                    .addComponent(Button_BoxRandom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Main.setBorder(javax.swing.BorderFactory.createTitledBorder("Main Image Points"));

        Button_PointSelected.setText("Selected");
        Button_PointSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PointSelectedMouseClicked(evt);
            }
        });

        Button_PointRandom.setText("Random");
        Button_PointRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PointRandomMouseClicked(evt);
            }
        });

        Button_PointSampled.setText("Sampled");
        Button_PointSampled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PointSampledMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_MainLayout = new javax.swing.GroupLayout(Panel_Main);
        Panel_Main.setLayout(Panel_MainLayout);
        Panel_MainLayout.setHorizontalGroup(
            Panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_MainLayout.createSequentialGroup()
                        .addComponent(Button_PointSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_PointRandom))
                    .addComponent(Button_PointSampled))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_MainLayout.setVerticalGroup(
            Panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_PointSelected)
                    .addComponent(Button_PointRandom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_PointSampled)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Zoom.setBorder(javax.swing.BorderFactory.createTitledBorder("Zoom Image Points"));

        Button_PointZoom.setText("Selected Point");
        Button_PointZoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PointZoomMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ZoomLayout = new javax.swing.GroupLayout(Panel_Zoom);
        Panel_Zoom.setLayout(Panel_ZoomLayout);
        Panel_ZoomLayout.setHorizontalGroup(
            Panel_ZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ZoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_PointZoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ZoomLayout.setVerticalGroup(
            Panel_ZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ZoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_PointZoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Zoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Boxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Panel_Boxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Zoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_OK)
                    .addComponent(Button_Cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BoxSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_BoxSelectedMouseClicked
        this.fcc.setButton(Button_BoxSelected);
        fcc.setVisible(true);
    }//GEN-LAST:event_Button_BoxSelectedMouseClicked

    private void Button_BoxRandomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_BoxRandomMouseClicked
        this.fcc.setButton(Button_BoxRandom);
        fcc.setVisible(true);
    }//GEN-LAST:event_Button_BoxRandomMouseClicked

    private void Button_PointSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PointSelectedMouseClicked
        this.fcc.setButton(Button_PointSelected);
        fcc.setVisible(true);
    }//GEN-LAST:event_Button_PointSelectedMouseClicked

    private void Button_PointRandomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PointRandomMouseClicked
        this.fcc.setButton(Button_PointRandom);
        fcc.setVisible(true);
    }//GEN-LAST:event_Button_PointRandomMouseClicked

    private void Button_PointZoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PointZoomMouseClicked
        this.fcc.setButton(Button_PointZoom);
        fcc.setVisible(true);
    }//GEN-LAST:event_Button_PointZoomMouseClicked

    private void setParentColors() {
        fds.rectangleSelectedColor = this.Button_BoxSelected.getBackground();
        fds.rectangleRandomColor = this.Button_BoxRandom.getBackground();
        fds.pointSelectedColor = this.Button_PointSelected.getBackground();
        fds.pointRandomColor = this.Button_PointRandom.getBackground();
        fds.pointZoomColor = this.Button_PointZoom.getBackground();
        fds.sampledPointsColor = this.Button_PointSampled.getBackground();
    }

    private void Button_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_OKMouseClicked
        setParentColors();
        doneSelection=true;
        this.setVisible(false);
    }//GEN-LAST:event_Button_OKMouseClicked

    private void Button_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CancelMouseClicked
        doneSelection=true;
        this.setVisible(false);
    }//GEN-LAST:event_Button_CancelMouseClicked

    private void Button_PointSampledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PointSampledMouseClicked
        this.fcc.setButton(Button_PointSampled);
        fcc.setVisible(true);
    }//GEN-LAST:event_Button_PointSampledMouseClicked

    private void setColors() {
        this.Button_BoxSelected.setBackground(fds.rectangleSelectedColor);
        this.Button_BoxRandom.setBackground(fds.rectangleRandomColor);
        this.Button_PointSelected.setBackground(fds.pointSelectedColor);
        this.Button_PointRandom.setBackground(fds.pointRandomColor);
        this.Button_PointZoom.setBackground(fds.pointZoomColor);
        this.Button_PointSampled.setBackground(fds.sampledPointsColor);     
    }

    public void disableColorSecting() {
        setColors();
        Button_BoxRandom.setEnabled(false);
        Button_BoxSelected.setEnabled(false);
        Button_PointRandom.setEnabled(false);
        Button_PointSampled.setEnabled(false);
        Button_PointSelected.setEnabled(false);
        Button_PointZoom.setEnabled(false);
    }

    boolean doneSelection = false;
    
    Frame_DataSampler fds;
    Frame_ColorChooser fcc;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_BoxRandom;
    private javax.swing.JButton Button_BoxSelected;
    private javax.swing.JButton Button_Cancel;
    private javax.swing.JButton Button_OK;
    private javax.swing.JButton Button_PointRandom;
    private javax.swing.JButton Button_PointSampled;
    private javax.swing.JButton Button_PointSelected;
    private javax.swing.JButton Button_PointZoom;
    private javax.swing.JPanel Panel_Boxes;
    private javax.swing.JPanel Panel_Main;
    private javax.swing.JPanel Panel_Zoom;
    // End of variables declaration//GEN-END:variables
}
