
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author dhearn
 */
public class Frame_SelectImagesDirectory extends javax.swing.JFrame {

    /**
     * Creates new form Frame_SelectImagesDirectory
     */
    public Frame_SelectImagesDirectory(Frame_DataSampler f_ds) {
        this.f_ds = f_ds;
        initComponents();
        if (f_ds.getRootDirectory() != null && f_ds.defaultImagesDirectory!=null) {
            currentDirectory = f_ds.getRootDirectory() + File.separator + f_ds.defaultImagesDirectory;
            FileChooser_SelectImagesDirectory.setCurrentDirectory(new File(currentDirectory));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser_SelectImagesDirectory = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileChooser_SelectImagesDirectory.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        FileChooser_SelectImagesDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooser_SelectImagesDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileChooser_SelectImagesDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileChooser_SelectImagesDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileChooser_SelectImagesDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooser_SelectImagesDirectoryActionPerformed
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            //String parentDir = FileChooser_SelectImagesDirectory.getCurrentDirectory().getParentFile().getAbsolutePath();
            
            currentDirectory = FileChooser_SelectImagesDirectory.getCurrentDirectory().getAbsolutePath();
            String fileName = FileChooser_SelectImagesDirectory.getSelectedFile().getName();
            f_ds.setImagesDirectory(fileName, currentDirectory, false);
            if (f_ds.getRootDirectory() == null) {
                f_ds.setRootDirectory(FileChooser_SelectImagesDirectory.getCurrentDirectory().getParentFile().getAbsolutePath());
            }
            this.setVisible(false);
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_FileChooser_SelectImagesDirectoryActionPerformed

    public void setDirectory() {
        try {
            FileChooser_SelectImagesDirectory.setCurrentDirectory(new File(currentDirectory));
        } catch (Exception e) {
            //System.out.println("Directory not set");
        }
    }

    private String currentDirectory;
    private final Frame_DataSampler f_ds;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser_SelectImagesDirectory;
    // End of variables declaration//GEN-END:variables
}
