
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author David
 */
public class Frame_SelectRootDirectory extends javax.swing.JFrame {

    /**
     * Creates new form Frame_SelectRootDirectory
     */
    public Frame_SelectRootDirectory(Frame_SetUserInfo fsui) {
        
        
        this.fsui = fsui;
        initComponents();
        
        if (fsui.getRootDirectory() != null ) {
            currentDirectory = fsui.getRootDirectory() ;
            FileChooser_SelectRoot.setCurrentDirectory(new File(currentDirectory));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser_SelectRoot = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileChooser_SelectRoot.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        FileChooser_SelectRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooser_SelectRootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileChooser_SelectRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FileChooser_SelectRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileChooser_SelectRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooser_SelectRootActionPerformed
        if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            
            
            //currentDirectory = FileChooser_SelectRoot.getCurrentDirectory().getAbsolutePath();
            
            currentDirectory = FileChooser_SelectRoot.getSelectedFile().getAbsolutePath();
            setDirectory(currentDirectory);
            
            fsui.setRootDirectory(currentDirectory);
            this.setVisible(false);
        } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_FileChooser_SelectRootActionPerformed

    
    public void setDirectory(String directory) {
        try {
            this.currentDirectory = directory;
            FileChooser_SelectRoot.setCurrentDirectory(new File(currentDirectory));
        } catch (Exception e) {
            //System.out.println("Directory not set");
        }
    }

    
    
    Frame_SetUserInfo fsui;
    String currentDirectory;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser_SelectRoot;
    // End of variables declaration//GEN-END:variables
}
