nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.1a.txt\", nrep = 1000, seed=1001, append=F)" > screen1.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.2a.txt\", nrep = 1000, seed=2001, append=F)" > screen2.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.3a.txt\", nrep = 1000, seed=3001, append=F)" > screen3.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.4a.txt\", nrep = 1000, seed=4001, append=F)" > screen4.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.5a.txt\", nrep = 1000, seed=5001, append=F)" > screen5.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.6a.txt\", nrep = 1000, seed=6001, append=F)" > screen6.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.7a.txt\", nrep = 1000, seed=7001, append=F)" > screen7.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.8a.txt\", nrep = 1000, seed=8003, append=T)" >> screen8.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.9a.txt\", nrep = 1000, seed=9001, append=F)" > screen9.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.10a.txt\", nrep = 1000, seed=10001, append=F)" > screen10.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.11a.txt\", nrep = 1000, seed=11001, append=F)" > screen11.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.12a.txt\", nrep = 1000, seed=12001, append=F)" > screen12.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.13a.txt\", nrep = 1000, seed=13001, append=F)" > screen13.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.14a.txt\", nrep = 1000, seed=14001, append=F)" > screen14.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.15a.txt\", nrep = 1000, seed=15001, append=F)" > screen15.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.16a.txt\", nrep = 1000, seed=16001, append=F)" > screen16.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.17a.txt\", nrep = 1000, seed=17001, append=F)" > screen17.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.18a.txt\", nrep = 1000, seed=18001, append=F)" > screen18.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.19a.txt\", nrep = 1000, seed=19001, append=F)" > screen19.txt 2> /dev/null &
nohup R --vanilla -e "source(\"examineMLE.R\"); run_Analysis5(outputFile = \"output.I.20a.txt\", nrep = 1000, seed=20001, append=F)" > screen20.txt 2> /dev/null &
